### ISSUE TITLE
Various Issues with different versions of the Xamarin iOS plugin including the latest Beta version

### ISSUE THREAD

**Issue by jcus0006** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#87]
## Expected Behavior

Accessing the plugin should show the Browse button to pick files from iCloud. Should work on both iPhones and iPads, particularly with the latest version/s. 

## Actual Behavior

With **Beta version 2.0.81** I get a System.IO.DirectoryNotFoundException - Could not find a part of the path... The path of the file retrieved from iCloud looks like the below:

 "file:///private/var/mobile/Containers/Data/Application/E4D562B3-0D10-4DEB-BAA2-742A69E034D9/tmp/com.atech.s2x.qm-Inbox/Mary.pdf\"

where com.atech.s2x.qm refers to the bundle identifier of the app.

With **Beta version 2.0.64**, it works on iPhone, but nothing happens on iPad. The Browse button does not appear.

With the **latest stable version** it gives me this error: 

> {System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

## Steps to Reproduce the Problem

Beta Version 2.0.81 - The app lets you choose the file and afterwards it crashes with the System.IO.DirectoryNotFoundException.

Beta Version 2.0.64, works properly on iPhone. With iPad nothing happens, browse button does not come up.

With Latest Stable version, when plugin is accessed, the System.NotImplementedException is immediately returned.

## Specifications

  - NuGet package version: 2.0.81, 2.0.64, 1.2.1
  - Platform(s): Xamarin Forms (iOS case only)

**Comment by codercampos** [comment]
I'm getting the same issue. When it tries to get the file with the GetStream method, it uses a path like this:
```
/private/var/containers/Bundle/Application/8C167674-B7ED-452E-8647-D239C012F721/ToolApp.iOS.app/file:/private/var/mobile/Containers/Data/Application/3C24AC4F-82CB-4812-96EF-2607486590C7/tmp/com.xinobistudio.toolapp-Inbox/reporte.pdf
```

I think the path that is being used is wrong. I will try a workaround and let you know.

**Comment by codercampos** [comment]
@jcus0006 
I'm using a weird workaround but at least on iOS is working good:
Knowing the path of the file, I check if the file really exists with the Path class. Before checking this, We need to remove the "file://" characters that are on the FilePath property. After that, you can read the bytes of the file and do whatever you want. Maybe this can help you continue working and I will try to check what is wrong on the iOS side of the plugin.

```csharp
var file = await CrossFilePicker.Current.PickFile();
if (file == null) return;
var extension = Path.GetExtension(file.FilePath);
var path = file.FilePath.Replace("file://", "");
var exists = File.Exists(path);
if(!exists) return;
var fileData = File.ReadAllBytes(path);
```

**Comment by jcus0006** [comment]
@codercampos thanks a lot for taking the time to comment. I've been stuck for a few days so it's great to actually try something new. 

I have re-structured the code to leave the previous implementation intact for the Android case, and tried something similar to yours for the iOS case. I re updated to the latest Beta version 2.0.81 (as I was going to use the previous Beta version and simply not offer the File upload functionality for iPad) and selected a file from iCloud drive. 

Unfortunately, removing the file:// string from the path does not solve the issue of not being able to find the actual file, in fact, the File.Exists line is returning false for me. I initially thought the issue might be related to the fact that the path is automatically appending the bundle id of the app before the file name. But now that you told me it is working for you; I am confused. 

Are you selecting an item from the iCloud Drive? What extension is the file? Are you using a real device or simulator? And is it an iPhone or an iPad? - I have tested on an iPad for the time being.

**Comment by jcus0006** [comment]
@codercampos  I am looking at your path:

> /private/var/containers/Bundle/Application/8C167674-B7ED-452E-8647-D239C012F721/ToolApp.iOS.app/file:/private/var/mobile/Containers/Data/Application/3C24AC4F-82CB-4812-96EF-2607486590C7/tmp/com.xinobistudio.toolapp-Inbox/reporte.pdf

It is quite different than what I am getting from file.FilePath. My path looks like the second part of your path:

> "file:///private/var/mobile/Containers/Data/Application/8F914E65-E6A2-44E1-808F-DB8C015BCD78/tmp/com.avantech.scan2x.qm-Inbox/TiffWPSample.tiff"

This may explain why your fix is working for you but not for me, but I don't know why it happens and how to fix it. The first GUID in your path: 8C167674-B7ED-452E-8647-D239C012F721, is different than the second: 3C24AC4F-82CB-4812-96EF-2607486590C7, so I can't see how I could possibly create the preceding bit dynamically as a work around.

**Comment by jcus0006** [comment]
@codercampos I had the time to also test on an iPhone and your solution worked. Initially, I thought it had to do with cross-device inconsistency; working on iPhone and not on iPad as the initial case, but then I noticed that the reason it was not working for me was actually the fact that file.FilePath contains spaces which inside the string are represented by %20. When trying to run File.Exists on a path with %20 in the place of spaces, it just does not find the file.

To fix it I simply replaced any %20 characters to a space: " " which seems to work. 

Re-pasting your slightly modified code below.

```
var file = await CrossFilePicker.Current.PickFile();
if (file == null) return;
var extension = Path.GetExtension(file.FilePath);
var path = file.FilePath.Replace("file://", "").Replace("%20"," "); //**added replace function on %20 here**
var exists = File.Exists(path);
if(!exists) return;
var fileData = File.ReadAllBytes(path);
```

Thanks a lot man!

**Comment by codercampos** [comment]
@jcus0006 
Sorry, Just to get everything clear: the exception  throws me this path:
"/private/var/containers/Bundle/Application/8C167674-B7ED-452E-8647-D239C012F721/ToolApp.iOS.app/file:/private/var/mobile/Containers/Data/Application/3C24AC4F-82CB-4812-96EF-2607486590C7/tmp/com.xinobistudio.toolapp-Inbox/reporte.pdf"

But when I get the path from the FilePath it returns:
file:/private/var/mobile/Containers/Data/Application/3C24AC4F-82CB-4812-96EF-2607486590C7/tmp/com.xinobistudio.toolapp-Inbox/reporte.pdf

Based on this I came up with the removing "file://" thing.

But you came up with something I didn't think of. I will add your fix into my solution too to be aware of the "%20" characters. I hope also I can fix this and provide a solution from the plugin side. Thank you!

**Comment by VansW** [comment]
I tried accessing file using above mentioned way but it returns false when I check for file.exists.
When I checked for the directory upto the point where file name starts, the directory does exist. 
So for example.

System.IO.Directory.Exists("/private/var/mobile/Containers/Data/Application/XYZ-KEY/tmp/com.myapp.app-Inbox") 
Returns true.

However, When I do File.Exists("/private/var/mobile/Containers/Data/Application/XYZ-KEY/tmp/com.myapp.app-Inbox/myebook.pdf")
Returns false

Any idea why?

**Comment by jfversluis** [comment]
Good stuff guys, if you find anything for this I'll gladly accept a PR

**Comment by vividos** [comment]
I think the problem here is that somewhere, two full paths are concatenated; the part after the "file:" text looks like a complete path. I will check today with the iOS sample project.

**Comment by roberleitner** [comment]
One thing I've discovered is related to a solution suggested here: https://stackoverflow.com/a/48007752/641995

Specifically, when using `UIDocumentPickerMode.Import` which this project does, files left in the `tmp/com.bundleid-Inbox/` folder can be aggressively deleted by iOS if you wait too long to access them. 

1. Pick a file from iCloud, file gets copied to `tmp/com.bundleid-Inbox/file_name.ext`
2. Wait 30 seconds
3. Check `tmp/com.bundleid-Inbox/` directory contents
4. File is now gone

The suggested workaround was to immediately move the imported file one level up to `tmp` or to the app's sandbox. I ended up doing something like this:

```
var fileData = await CrossFilePicker.Current.PickFile(new string[] { "com.adobe.pdf" });

if (null == fileData)
{
    return null;
}

fileData.FilePath = fileData.FilePath.Replace("file://", "").Replace("%20", " ");

var tmpDir = Path.GetTempPath();
var tmpFile = Path.Combine(tmpDir, fileData.FileName);
if (File.Exists(tmpFile))
{
    File.Delete(tmpFile);
}
File.Move(fileData.FilePath, tmpFile);

return new FileData(tmpFile, fileData.FileName, () =>
{
    return new FileStream(tmpFile, FileMode.Open, FileAccess.Read);
});
```

FYI this will overwrite any files that already exist in the tmp directory that have the same name.

**Comment by vividos** [comment]
@ryanoberleitner Good info about the temp file being removed. What happens when you directly get a file stream after PickFile(), e.g. with fileData.GetStream(), wait for some seconds and then try to access the stream? My guess would be that the file is gone (check with File.Exists()), but the stream can be read from.

Generally, the fix for FilePath containing %20 characters and the file:// prefix is fixed in NuGet package 2.0.106-beta. Please try it out. Thanks!

**Comment by vividos** [comment]
Just to note, it seem it's the same crash as in #74.

**Comment by roberleitner** [comment]
@vividos Thanks for the update on nuget, the new beta appears to fix my issues on both Android and iOS.

> What happens when you directly get a file stream after PickFile(), e.g. with fileData.GetStream(), wait for some seconds and then try to access the stream? My guess would be that the file is gone (check with File.Exists()), but the stream can be read from.

I did a test with this that holds on to the tmp/com.bundle.id-Inbox FilePath and Stream from GetStream(). After waiting a bit, I looked for any files that returned false for File.Exists() and sure enough, I could still get bytes by calling FileData.ReadFully on that stream.

**Comment by vividos** [comment]
Well, then maybe the solution is to document the fact that iOS will remove the input file soon, so it's mandatory to save it to local storage. I think the CrossFilePicker.Current.SaveFile() method is used for that.

**Comment by vividos** [comment]
I now documented the behavior of iOS in the README so that other users don't fall into the same trap.
